# SPDX-FileCopyrightText: Copyright DB InfraGO AG
# SPDX-License-Identifier: CC0-1.0

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: wednesday
    groups:
      github-actions:
        patterns: ["*"]
    commit-message:
      prefix: chore
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
      day: wednesday
    allow:
      - dependency-type: development
    groups:
      python-packages:
        patterns: ["*"]
    commit-message:
      prefix: chore
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
      day: wednesday
    allow:
      - dependency-type: all
    groups:
      rust-deps:
        patterns: ["*"]
    commit-message:
      prefix: build(rust)
